/*
 * Copyright (c) 2016 Aaron Kondziela <aaron@aaronkondziela.com> 
 *
 * This file is part of ujson-c
 *
 * ujson-c is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ujson-c is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */
 
 /*
  * Part of ujson-c - Implements microjson in C - see ujson.org
  * and https://github.com/aaronkondziela/ujson-c/
  *
  * ujson-extract.c
  * de-serialize elements by applying a schema generated
  * by ujson-format, to data generated by ujson-data. Also used by
  * ujson-parse which handles inlined schemas.
  *
  */

#include "endian.h"
#include "movebytes.h"
#include "ujson-extract.h"

// you'll probably never use these bool and null extracts; included for structural symmetry
// perhaps to be removed later.
void extract_bool_true(uint8_t** nextbuf, uint8_t* val)
{
	*val = 1; 
}

void extract_bool_false(uint8_t** nextbuf, uint8_t* val)
{
	*val = 0; 
}

void extract_null(uint8_t** nextbuf, uint8_t* val)
{
	*val = 0;
}

void extract_uint8(uint8_t** nextbuf, uint8_t* val)
{
	*val = (uint8_t)(**nextbuf);
	(*nextbuf) += 1;
}

void extract_int8(uint8_t** nextbuf, int8_t* val)
{
	*val = (int8_t)(**nextbuf);
	(*nextbuf) += 1;
}

void extract_uint16(uint8_t** nextbuf, uint16_t* val)
{
	movebytes( (uint8_t*)val, *nextbuf, 2 );
	*val = htoj16(*val);
	(*nextbuf) += 2;
}

void extract_int16(uint8_t** nextbuf, int16_t* val)
{
	movebytes( (uint8_t*)val, *nextbuf, 2 );
	*val = htoj16(*val);
	(*nextbuf) += 2;
}

void extract_uint32(uint8_t** nextbuf, uint32_t* val)
{
	movebytes( (uint8_t*)val, *nextbuf, 4 );
	*val = htoj32(*val);
	(*nextbuf) += 4;
}

void extract_int32(uint8_t** nextbuf, int32_t* val)
{
	movebytes( (uint8_t*)val, *nextbuf, 4 );
	*val = htoj32(*val);
	(*nextbuf) += 4;
}

void extract_uint64(uint8_t** nextbuf, uint64_t* val)
{
	movebytes( (uint8_t*)val, *nextbuf, 8 );
	*val = htoj64(*val);
	(*nextbuf) += 8;
}

void extract_int64(uint8_t** nextbuf, int64_t* val)
{
	movebytes( (uint8_t*)val, *nextbuf, 8 );
	*val = htoj64(*val);
	(*nextbuf) += 8;
}

void extract_string(uint8_t** nextbuf, uint8_t* str)
{
	uint16_t len = 0;
	extract_uint16(nextbuf, &len);
	movebytes(str, *nextbuf, len);
	str[len] = '\0';
	(*nextbuf) += len;
}

void extract_float(uint8_t** nextbuf, float* val)
{
	movebytes( (uint8_t*)val, *nextbuf, 4 );
	*val = htojf(*val);
	(*nextbuf) += 4;
}

void extract_double(uint8_t** nextbuf, double* val)
{
	movebytes( (uint8_t*)val, *nextbuf, 8 );
	*val = htojd(*val);
	(*nextbuf) += 8;
}

// TODO
// extract() - apply schema to data




